### PR TITLE
Adressing the issues I mentioned

### PR DESCRIPTION
**Pull request by LMS0815**
This is to address the issues I raised in the master branch

### CODE REVIEW

**Comment by kantlivelong** [comment]
Can you let me know if 0.0.3 fixed your issue before continuing here?

#4

**Comment by kantlivelong** [comment]
Also let's work from #4 before looking at this. I'm not sure how you are able to print without selecting a file first.

**Comment by LMS0815** [comment]
See my comment on https://github.com/kantlivelong/OctoPrint-SmartPreheat/issues/4

**Comment by LMS0815** [comment]
Your new GCODE analyse function is much better (also I prefer mine :) ) but can be performance optimized. (Kindly check my approach)..
Please only use "WAIT tor temp" statements only for analysis (or offer an option in the plugin) as GCODE sometimes is using different temperatures for WAIT and SET.
I assume more important is the snippet. Your version is just not working on my LINUX and just throwing errors - which means aborting.

**Comment by LMS0815** [comment]
I you like to be inspired, just visit my fork.

**Pull request closed without merging**
